version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ws-db
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: ws-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=ws-db

volumes:
  db_data:
