apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-green       # Deployment name for green version
  labels:
    app: flask-app-green
spec:
  replicas: 2                 # Number of pod replicas
  selector:
    matchLabels:
      app: flask-app-green    # Selector that matches green version pods
  template:
    metadata:
      labels:
        app: flask-app-green
    spec:
      containers:
        - name: flask-app-container
          image: ruvini925/ws-coursework-web:latest   # Replace with your Docker image
          ports:
            - containerPort: 5000                  # Port exposed by your Flask app
      imagePullSecrets:
        - name: regcred  # Name of the Docker registry secret