apiVersion: v1
kind: Service
metadata:
  name: flask-app-service      # Service name
spec:
  selector:
    app: flask-app-blue        # Initially pointing to blue deployment
  ports:
    - protocol: TCP
      port: 80                   # External port for service
      targetPort: 5000           # Port exposed by Flask app inside the container
  type: LoadBalancer            # For cloud environments (e.g., AWS, GCP)
